import Navbar from "@/components/Navbar"
import AuthProvider from "@/context/AuthProvider"
import { SessionProvider } from "next-auth/react"
import './globals.css'
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">

            <body>
                <AuthProvider>
                    <Navbar />
                    {children}
                </AuthProvider>
            </body>

        </html>
    )
}
